export default [
  {
    text: "Examples",
    items: [
      { text: "Markdown Examples", link: "posts/markdown-examples" },
      { text: "Runtime API Examples", link: "posts/api-examples" },
      { text: "Markdown Examples", link: "posts/markdown-examples" },
      { text: "Runtime API Examples", link: "posts/api-examples" },
      { text: "Markdown Examples", link: "posts/markdown-examples" },
      { text: "Runtime API Examples", link: "posts/api-examples" },
      { text: "Markdown Examples", link: "posts/markdown-examples" },
      { text: "Runtime API Examples", link: "posts/api-examples" },
      { text: "Markdown Examples", link: "posts/markdown-examples" },
      { text: "Runtime API Examples", link: "posts/api-examples" },
      { text: "Markdown Examples", link: "posts/markdown-examples" },
      { text: "Runtime API Examples", link: "posts/api-examples" },
      { text: "Markdown Examples", link: "posts/markdown-examples" },
      { text: "Runtime API Examples", link: "posts/api-examples" },
      { text: "Markdown Examples", link: "posts/markdown-examples" },
      { text: "Runtime API Examples", link: "posts/api-examples" },
      { text: "Markdown Examples", link: "posts/markdown-examples" },
      { text: "Runtime API Examples", link: "posts/api-examples" },
      { text: "Markdown Examples", link: "posts/markdown-examples" },
      { text: "Runtime API Examples", link: "posts/api-examples" },
      { text: "Markdown Examples", link: "posts/markdown-examples" },
      { text: "Runtime API Examples", link: "posts/api-examples" },
      { text: "Markdown Examples", link: "posts/markdown-examples" },
      { text: "Runtime API Examples", link: "posts/api-examples" },
      { text: "Markdown Examples", link: "posts/markdown-examples" },
      { text: "Runtime API Examples", link: "posts/api-examples" },
      { text: "Markdown Examples", link: "posts/markdown-examples" },
      { text: "Runtime API Examples", link: "posts/api-examples" },
      { text: "Markdown Examples", link: "posts/markdown-examples" },
      { text: "Runtime API Examples", link: "posts/api-examples" },
      { text: "Markdown Examples", link: "posts/markdown-examples" },
      { text: "Runtime API Examples", link: "posts/api-examples" },
      { text: "Markdown Examples", link: "posts/markdown-examples" },
      { text: "Runtime API Examples", link: "posts/api-examples" },
      { text: "Markdown Examples", link: "posts/markdown-examples" },
      { text: "Runtime API Examples", link: "posts/api-examples" },
      { text: "Markdown Examples", link: "posts/markdown-examples" },
      { text: "Runtime API Examples", link: "posts/api-examples" },
      { text: "Markdown Examples", link: "posts/markdown-examples" },
      { text: "Runtime API Examples", link: "posts/api-examples" },
      { text: "Markdown Examples", link: "posts/markdown-examples" },
      { text: "Runtime API Examples", link: "posts/api-examples" },
    ],
  },
];
